display_name: Floaty Nightly
package_name: Floaty-Nightly
maintainer:
  name: bw86
  email: hello@autow.in
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/nightly_icon.png

keywords:
  - Floatplane
  - Floaty
  - Whenplane

generic_name: Video Application

categories:
  - AudioVideo

startup_notify: true
# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml