# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: floaty-floatplane-client-release
publisher: bw86
publisher_url: https://floaty.fyi
display_name: Floaty
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
install_dir_name: "D:\\FloatyRelease"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
setup_icon_file: assets/icon/release_icon_win.ico
locales:
  - en